#!/bin/sh
# Simple script to see how long someone's been following a channel
# Usage: tw-follow channel user
if [ ! $# = 2 ] ; then
	echo "tw-follow <channel> <user>"
	exit 1
fi
ACCOUNT=$2
CHANNEL=$1
curl "https://api.2g.be/twitch/followage/${CHANNEL}/${ACCOUNT}?format=mwdhms"
echo

